const exportToFile = (filename, text) => {
    let element = document.createElement('a');
    element.setAttribute('href', 'data:text/html;charset=UTF-8,' + encodeURIComponent(
        htmlBefore + text + htmlAfter
    ));
    element.setAttribute('download', 'planrr_' + filename);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
}

let style = '@import url(https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap);*{box-sizing:border-box;font-family:Poppins,sans-serif}body{overflow:hidden;margin:0;width:100%;height:100%;background:#444 url("https://neostetic.github.io/Planrr/res/assets/bg-tile.png") repeat}.noselect,br,button,img{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}::-moz-selection{color:#000;background:rgba(0,0,0,.3)}::selection{color:#000;background:rgba(0,0,0,.3)}.canvas{top:50%;left:50%;transform:translate(-50%,-50%);width:500px;height:500px;position:absolute;background:#fff;border:1px solid rgba(0,0,0,.3);box-shadow:0 0 20px rgba(0,0,0,.2);transition:.2s}.block{position:absolute;float:left;border-radius:8px;overflow:hidden;box-shadow:0 0 20px rgba(0,0,0,.2);border:2px solid rgba(0,0,0,.2)}.dragger{width:100%;padding:14px;background:rgba(0,0,0,.07);cursor:move}.textarea{resize:none;min-width:200px;min-height:120px;max-width:1000px;max-height:1000px;position:relative;top:7px;outline:0;border:none;padding:3px 10px 10px 10px;font-size:18px;background:0 0;overflow:hidden}.textarea::before{position:absolute;top:-200px;content:\'where\';background:#7051ff}::placeholder{color:rgba(0,0,0,.4)}.button-menu{position:absolute;top:0;right:0;margin:10px;display:flex;flex-direction:column}.button-menu-second{position:absolute;bottom:0;left:0;margin:10px;display:none;flex-direction:column}.button{position:relative;float:right;width:60px;height:60px;margin:10px;padding:16px;background:#fff;border-radius:10px;box-shadow:0 0 20px rgba(0,0,0,.3);cursor:pointer;transition:.2s}.button:hover{transform:scale(1.05)}.button:active{padding:14px}.move-svg{position:relative;top:-2px;left:5px;width:16px}.move-svg-2{position:relative;top:-4px}#loader{top:0;left:0;position:absolute;background:#fff;width:100vw;height:100vh;transition:.5s}#loader>div>h1{color:#7051ff}.loader{width:400px;height:10px;border:1px solid rgba(0,0,0,.2);border-radius:20px;background:url("https://neostetic.github.io/Planrr/res/assets/bg-loader.png") repeat;animation:loaderSpin infinite .4s linear}@keyframes loaderSpin{from{background-position-x:40px}to{background-position-x:0}}.center-element{position:absolute;top:50%;left:50%;text-align:center;transform:translate(-50%,-50%)}@media screen and (max-width:600px){#newfile,.info-box>div>textarea{width:70vw}button>span{display:none}button{font-size:12px}button>svg{margin-right:0}.changeBgs{width:70vw}.loader{width:50vw}}'
let script = 'window.addEventListener("load",async e=>{document.getElementById("loader").style.opacity="0",await sleep(500),document.getElementById("loader").style.display="none"});let upCameraButton=document.getElementById("upCameraButton"),downCameraButton=document.getElementById("downCameraButton"),leftCameraButton=document.getElementById("leftCameraButton"),rightCameraButton=document.getElementById("rightCameraButton"),zoomInButton=document.getElementById("zoomInButton"),zoomOutButton=document.getElementById("zoomOutButton"),centerCameraButton=document.getElementById("centerCameraButton"),yCameraIndex=0,xCameraIndex=0,canvasScale=1;zoomInButton.onclick=(()=>{canvasScale+=.1,canvas.style.transform="translate(-50%, -50%) scale("+canvasScale+")"}),zoomOutButton.onclick=(()=>{canvasScale>.3&&(canvasScale-=.1),canvas.style.transform="translate(-50%, -50%) scale("+canvasScale+")"}),upCameraButton.onclick=(()=>{yCameraIndex+=10,canvas.style.top=50+yCameraIndex+"%"}),downCameraButton.onclick=(()=>{yCameraIndex-=10,canvas.style.top=50+yCameraIndex+"%"}),leftCameraButton.onclick=(()=>{xCameraIndex+=10,canvas.style.left=50+xCameraIndex+"%"}),rightCameraButton.onclick=(()=>{xCameraIndex-=10,canvas.style.left=50+xCameraIndex+"%"}),centerCameraButton.onclick=(()=>{centerCamera()});const centerCamera=()=>{canvasScale=1,xCameraIndex=0,yCameraIndex=0,canvas.style.top=50+yCameraIndex+"%",canvas.style.left=50+xCameraIndex+"%",canvas.style.transform="translate(-50%, -50%) scale("+canvasScale+")",popupShow("Centered")};function sleep(e){return new Promise(n=>setTimeout(n,e))};'
let htmlBefore = '<!doctypehtml><html lang=en><meta charset=UTF-8><title>Export | PLANRR</title><style>' + style + '</style><meta content="width=device-width,initial-scale=1"name=viewport>'
let htmlAfter = '<div class=noselect id=loader><div class=center-element><h1>Planrr</h1><div class=loader></div></div></div><script>' + script + '</script></body></html>'